# Generated by Django 3.0 on 2019-12-04 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbproducts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_as_original', to='dbproducts.Product')),
                ('substitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_as_substitute', to='dbproducts.Product')),
            ],
        ),
    ]
