# Generated by Django 3.0 on 2019-12-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=250)),
                ('img_front_url', models.URLField(max_length=255)),
                ('nutri_grade', models.IntegerField()),
                ('img_nutrition_url', models.URLField(max_length=255)),
                ('web_link', models.URLField(max_length=255)),
                ('categories', models.ManyToManyField(to='dbproducts.Category')),
            ],
        ),
    ]
