# Generated by Django 3.0 on 2019-12-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbproducts', '0002_auto_20191204_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='web_link',
            field=models.URLField(max_length=255),
        ),
    ]
